name: Simulated Jenkins Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Jenkinsfile
        uses: jenkinsci/jenkinsfile-runner-github-action@v1

